import = [
  "~/.config/alacritty/catppuccin-latte.toml"
]

[window]
# opacity = 0.8

padding.x = 4
padding.y = 4

[font]
size = 10.0

offset.x = 0  # For letter spacing (default: 0)
offset.y = 0  # For line spacing (default: 0)

[env]
TERM = "xterm-256color"
