# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/wmqx0f9rcr89madbri0df48mqkq56akw-hm-session-vars.fish



status --is-login; and begin

    # Login shell initialisation

    if test -z "$DISPLAY" -a "$XDG_VTNR" = 1
        exec /usr/bin/sway
    end


end

status --is-interactive; and begin

    # Abbreviations
    abbr --add -- dk 'cd ~/nix; nix run github:serokell/deploy-rs .#kali'
    abbr --add -- dr 'cd ~/nix; nix run github:serokell/deploy-rs .#robert'
    abbr --add -- hs 'cd ~/nix; home-manager switch --flake .#usd'
    abbr --add -- l 'ls -lah'
    abbr --add -- vim nvim

    # Aliases


    # Interactive shell initialisation
    source /nix/store/9khhs77f5347gy80v55z5pv375bymbj8-atelier-lakeside/base16-atelier-lakeside.fish
    base16-atelier-lakeside

    set -g fish_greeting

    if test "$TERM" != dumb
        eval (/home/ehud/.nix-profile/bin/starship init fish)

    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/ehud/.local/share/fish/home-manager_generated_completions" $post
    end

    . /nix/store/af8aianpx1k4h5zmnp0wk466q5svrkyk-autojump-22.5.3/share/autojump/autojump.fish

    /nix/store/3bmgmpaqm8p34hi6xb1y4fisf5n0pbbh-direnv-2.34.0/bin/direnv hook fish | source


end
