#!/bin/bash

# Check if "fritz.box" is present in /etc/resolv.conf
if /usr/bin/grep -q "fritz.box" /etc/resolv.conf; then
    # Connected to home network, no action necessary.
    /usr/bin/echo "== Detected Home Network =="

else
    # Execute a different command if "fritz.box" is not found
    /usr/bin/echo "== Detected office network, connecting to VLAN =="

    /usr/bin/nmcli connection down Wired\ connection\ 1
    /usr/bin/nmcli connection up net_client_pen && /usr/bin/notify-send --urgency normal --expire-time 5000 "VLAN connected" "You are now connected to the Pentest network."
fi

