#!/bin/bash

# Setting Display Resolution
main_display="eDP1"
home_front="DP2-2"
home_right="DP2-1"
office_front="DP-2-8"
office_left="DP-2-1"

set_wallpaper() { 
	# /usr/bin/feh --bg-fill /home/nbetz/Pictures/Wallpapers/abstracts-paint-3440x1440-v0-6y2zjgl0744c1; 
	/home/nbetz/.local/bin/wal -R
}

send_notification()
{
  /usr/bin/notify-send --urgency normal --expire-time 5000 "Monitor Setup detected" "$1"
}

# The following order is important, as some cases detect monitors, that are available in all 3 configurationse:
# Case: Office + HP Docking station
if /usr/bin/xrandr | grep -q "DP2-3 connected"; then
  echo "Office monitors (HP Docking Station) detected. Setting configuration accordingly..."

  /usr/bin/xrandr --output eDP1 --mode 1920x1080 --pos 3840x0 --rotate normal --output DP2-1 --off --output DP2-2 --mode 1920x1080 --pos 0x0 --rotate normal --output DP2-3 --primary --mode 1920x1080 --pos 1920x0 --rotate normal

  send_notification "Your setup was configured for your HP docking station."
  set_wallpaper
  exit 0
fi

# Case: Home Office
if /usr/bin/xrandr | grep -q "DP2-1 connected"; then
  echo "Home monitors detected. Setting configuration accordingly..."

 # /usr/bin/xrandr --output $home_front --mode 2560x1080 --primary --right-of $main_display --output $home_right --mode 2560x1080 --right-of $home_front
#  /usr/bin/xrandr --output eDP-1 --off --output DP-2-1 --mode 2560x1080 --pos 2560x0 --rotate normal --output DP-2-2 --primary --mode 2560x1080 --pos 0x0 --rotate normal
  /usr/bin/xrandr --output eDP-1 --off --output DP-2-1 --mode 2560x1080 --pos 2560x0 --rotate normal --output DP-2-2 --primary --mode 2560x1080 --pos 0x0 --rotate normal
  
  send_notification "Your setup was configured for your home monitors."
  set_wallpaper
  exit 0
fi

# Case: Office 
if /usr/bin/xrandr | grep -q "DP2-8 connected"; then
  echo "Office monitors detected. Setting configuration accordingly..."

  # /usr/bin/xrandr --output $main_display --mode 1920x1080 --output $office_front --primary --mode 1920x1080 --above $main_display --output $office_left --mode 1920x1080 --left-of $office_front
  /usr/bin/xrandr --output $main_display --mode 1920x1080 --pos 0x360 --rotate normal --output $office_front --primary --mode 2560x1440 --pos 1920x0 --rotate normal --output $office_left --mode 2560x1440 --pos 4480x0 --rotate normal

  send_notification "Your setup was configured for your office monitors."
  set_wallpaper
  exit 0
fi

if /usr/bin/xrandr | grep -q " connected"; then
	echo "No monitors, using main monitor instead"

	/usr/bin/xrandr --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --off --output DP2 --off --output DP2-1 --off --output DP2-2 --off --output DP2-3 --off --output DP3 --off --output DP4 --off --output HDMI1 --off --output VIRTUAL1 --off

	send_notification "Your setup was configured for notebook only use"

	set_wallpaper
	exit 0
fi

